### ISSUE TITLE
Throttle strategy based on number of served requests

### ISSUE THREAD

**Issue by h2non** [PuerkitoBio/throttled#5]
What about introducing support for a new throttle strategy based on the number of concurrent pending request to serve instead of a time window frame size? Just like a FIFO queue

I found this quite useful for some specific complex multithreading scenarios, which I think it's actually more reliable than a time window frame based limit

**Comment by PuerkitoBio** [comment]
Hi Tomas,

You mean something like `throttle.Concurrent(concurrentRequests int, bursts int, varyBy *throttled.VaryBy, maxKeys int)`?

Technically it should be doable using the Custom throttling hook. I'm personally not interested in implementing new strategies for this package, but if someone wants it enough to send a PR with good tests and documentation, I'd merge it. Sounds like a nice companion to the other throttlers.

Note that if you don't need the vary-by and routing features of throttled, you can do this more efficiently using token buckets (e.g. http://godoc.org/github.com/juju/ratelimit).

Martin

**Comment by h2non** [comment]
Thank you for the info. Probably I'll try it out by myself and if the solution for my particular scenario is useful for other ones I'll purpose it here as PR.

Regarding to the issue, for me is enough. Feel free to close it.
