### ISSUE TITLE
Add Retry-After HTTP header

### ISSUE THREAD

**Issue by h2non** [PuerkitoBio/throttled#7]
This standard header defined in the RFC could be defined when the server replies with both 503 or 429 status codes. I think it could be defined as optional feature enabled by the user. 

For some scenarios it could be useful since some HTTP implementors already support it, and by other hand it will delegate the retry logic on the HTTP client, simplifying the things to the end consumer.

The retry delay could be specified by the user or dynamically calculated based on the response time of the already served requests.

Spec: 
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.37

A bit of info about the current support state:
http://stackoverflow.com/questions/3764075/retry-after-http-response-header-does-it-affect-anything

For instance, HAProxy implements it in some cases.

**Comment by PuerkitoBio** [comment]
Unless I misunderstand, this is already done when the limit is reached: 

https://github.com/PuerkitoBio/throttled/blob/master/rate.go#L111

Do you have something else in mind?

Thanks,
Martin

**Comment by h2non** [comment]
Ouch! It was my mistake. I did a brief code search to find it out, but I didn't found it (probably due to a bad typing).

So, excellent, Nothing more to add. Closing

**Comment by PuerkitoBio** [comment]
Cool, no problem!
